package rumahsakit;

public class menuUtama extends javax.swing.JFrame {

    /**
     * Creates new form menuUtama
     */
    public menuUtama() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        inputPasien = new javax.swing.JMenuItem();
        inputDokter = new javax.swing.JMenuItem();
        inputPerawat = new javax.swing.JMenuItem();
        inputPenyakit = new javax.swing.JMenuItem();
        inputKunjung = new javax.swing.JMenuItem();
        EXIT = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        dataPasien = new javax.swing.JMenuItem();
        dataDokter = new javax.swing.JMenuItem();
        dataPerawat = new javax.swing.JMenuItem();
        dataPenyakit = new javax.swing.JMenuItem();
        dataKunjung = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Rumah Sakit");
        setForeground(new java.awt.Color(0, 0, 102));

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jLabel2.setFont(new java.awt.Font("Bell MT", 1, 48)); // NOI18N
        jLabel2.setText("Rumah Sakit");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.setMaximumSize(new java.awt.Dimension(150, 16));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(168, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(157, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150))
        );

        jMenuBar2.setBackground(new java.awt.Color(153, 153, 153));

        jMenu3.setForeground(new java.awt.Color(255, 255, 255));
        jMenu3.setText("MENU INPUT");

        inputPasien.setText("INPUT PASIEN");
        inputPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPasienActionPerformed(evt);
            }
        });
        jMenu3.add(inputPasien);

        inputDokter.setText("INPUT DOKTER");
        inputDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputDokterActionPerformed(evt);
            }
        });
        jMenu3.add(inputDokter);

        inputPerawat.setText("INPUT PERAWAT");
        inputPerawat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPerawatActionPerformed(evt);
            }
        });
        jMenu3.add(inputPerawat);

        inputPenyakit.setText("INPUT PENYAKIT");
        inputPenyakit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPenyakitActionPerformed(evt);
            }
        });
        jMenu3.add(inputPenyakit);

        inputKunjung.setText("REKAM MEDIS");
        inputKunjung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputKunjungActionPerformed(evt);
            }
        });
        jMenu3.add(inputKunjung);

        EXIT.setText("EXIT");
        EXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXITActionPerformed(evt);
            }
        });
        jMenu3.add(EXIT);

        jMenuBar2.add(jMenu3);

        jMenu4.setForeground(new java.awt.Color(255, 255, 255));
        jMenu4.setText("MENU DATA");

        dataPasien.setText("DATA PASIEN");
        dataPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataPasienActionPerformed(evt);
            }
        });
        jMenu4.add(dataPasien);

        dataDokter.setText("DATA DOKTER");
        dataDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataDokterActionPerformed(evt);
            }
        });
        jMenu4.add(dataDokter);

        dataPerawat.setText("DATA PERAWAT");
        dataPerawat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataPerawatActionPerformed(evt);
            }
        });
        jMenu4.add(dataPerawat);

        dataPenyakit.setText("DATA PENYAKIT");
        dataPenyakit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataPenyakitActionPerformed(evt);
            }
        });
        jMenu4.add(dataPenyakit);

        dataKunjung.setText("DATA KUNJUNG");
        dataKunjung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataKunjungActionPerformed(evt);
            }
        });
        jMenu4.add(dataKunjung);

        jMenuBar2.add(jMenu4);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPasienActionPerformed
        inputPasien ip = new inputPasien();
        ip.setVisible(true);
    }//GEN-LAST:event_inputPasienActionPerformed

    private void inputDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputDokterActionPerformed
        inputDokter iDok = new inputDokter();
        iDok.setVisible(true);
    }//GEN-LAST:event_inputDokterActionPerformed

    private void inputPerawatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPerawatActionPerformed
        inputPerawat iPer = new inputPerawat();
        iPer.setVisible(true);
    }//GEN-LAST:event_inputPerawatActionPerformed

    private void inputPenyakitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPenyakitActionPerformed
        inputPenyakit iPen = new inputPenyakit();
        iPen.setVisible(true);
    }//GEN-LAST:event_inputPenyakitActionPerformed

    private void inputKunjungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputKunjungActionPerformed
        inputKunjung iKun = new inputKunjung();
        iKun.setVisible(true);
    }//GEN-LAST:event_inputKunjungActionPerformed

    private void EXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXITActionPerformed
        System.exit(0);
    }//GEN-LAST:event_EXITActionPerformed

    private void dataPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataPasienActionPerformed
        dataPasien dPas = new dataPasien();
        dPas.setVisible(true);
    }//GEN-LAST:event_dataPasienActionPerformed

    private void dataDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataDokterActionPerformed
        dataDokter dDok = new dataDokter();
        dDok.setVisible(true);
    }//GEN-LAST:event_dataDokterActionPerformed

    private void dataPerawatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataPerawatActionPerformed
        dataPerawat dPer = new dataPerawat();
        dPer.setVisible(true);
    }//GEN-LAST:event_dataPerawatActionPerformed

    private void dataPenyakitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataPenyakitActionPerformed
        dataPenyakit dPen = new dataPenyakit();
        dPen.setVisible(true);
    }//GEN-LAST:event_dataPenyakitActionPerformed

    private void dataKunjungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataKunjungActionPerformed
        dataKunjung dKun = new dataKunjung();
        dKun.setVisible(true);
    }//GEN-LAST:event_dataKunjungActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new menuUtama().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem EXIT;
    private javax.swing.JMenuItem dataDokter;
    private javax.swing.JMenuItem dataKunjung;
    private javax.swing.JMenuItem dataPasien;
    private javax.swing.JMenuItem dataPenyakit;
    private javax.swing.JMenuItem dataPerawat;
    private javax.swing.JMenuItem inputDokter;
    private javax.swing.JMenuItem inputKunjung;
    private javax.swing.JMenuItem inputPasien;
    private javax.swing.JMenuItem inputPenyakit;
    private javax.swing.JMenuItem inputPerawat;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
